### ISSUE TITLE
UI/UX Choice | Pick a symbol for rounded units

### ISSUE THREAD

**Issue by sahebdas** [spartan-protocol/SpartanProtocol-DAppV2#534]
**Describe the bug**
Token balance is rounded off and shown in system. However the user can't use the exact amount shown in the system. User has to select 'MAX' button to use its maximum balance which is always less than the balance(rounded off) shown in the system.

**To Reproduce**
1. Go to 'BNB' section
2. Click on 'SWAP'
3. Check your BNB Balance as shown
4. Try to enter the exact amount for sell
5. See error as 'Check Balance' button will appear instead of 'Sell BNB'

**Expected behavior**
My actual BNB-1.4948529
option 1. Show approximate keyword beside balance like 'Balance: 1.4949(approx)'.
option 2. Do not round off the amount like 'Balance: 1.4948'.

**Screenshots**
![snapshot1](https://user-images.githubusercontent.com/90037936/134940948-d92492d2-0c3d-43e5-9aae-879bd1a0d24b.png)
![snapshot2](https://user-images.githubusercontent.com/90037936/134940950-c09ac10f-12b4-4895-8f7c-1dd03d23ac49.png)

**Desktop (please complete the following information):**
- Wallet -MetaMask 
 - OS: Windows 10
 - Browser -chrome, brave

**Your BSC Wallet Address**
0x5Aa1eba0c0ecE56E198c289AC413Ba4BD4bfA700

**Comment by SamusElderg** [comment]
> An ~ would be pretty clear and should be understandable by most users.
> 
> Also, if a user's input is over the balance, maybe we could simply replace it automatically by the balance value ?

Awesome; that's a vote for '~' 👍 

Whilst the second part of your comment is a good suggestion for the user who is only worried about using 100% of their balance (having said that; that's what the MAX button is for), it doesn't account for the rest of users. We need users to be able to input a larger amount than they have in their wallet to simulate the output/market. 

It's normal & expected UX to be able to either have no wallet connected and input > 0 units, or their wallet connected (which maybe they haven't transferred over the amount they want to swap yet) and simulate the output if they *did* have the amount. Might also be tricky to make it clear the DApp has capped the input for the user. I think the current behaviour is good/expected; and the button changing to 'check balance' makes it clear anyway. The only issue for me is the visual rounding of units throughout the dapp; if we nail that then we are A-OK!

Another thing we can do is trim the last decimal so that the number shown is always 1 decimal shorter than the actual number and therefore technically rounded down or 'floored' but i suspect we wont need to do that if we nail the icon/tooltip
