### ISSUE TITLE
BUG |  NOT A BUG BUT UX SUGGESTIONS

### ISSUE THREAD

**Issue by Sonos21** [spartan-protocol/SpartanProtocol-DAppV2#551]
Hi Samus

As discussed , here are my considerations regarding the current Sparta UX and some suggestions for improvement

All to try to make SPARTA the best platform for (passive) income streams on Binance

ongoing work...and open for ideas/suggestions
[Sparta Protocol Testnet V2.1 4_10_2021   UX suggestions .pdf](https://github.com/spartan-protocol/SpartanProtocol-DAppV2/files/7278206/Sparta.Protocol.Testnet.V2.1.4_10_2021.UX.suggestions.pdf)

i hope the screenshots are good enough, else let me know...

talk soon
Sonos21

**Comment by SamusElderg** [comment]
Have added the 'menu' issue to GitHub; this menu behaviour/style was only intended for these earlier phases; we had a full double-component menu for different device types (similar to what you want) initially in DAppV2 but ripped all of that out for the BUIDl stages as it makes more sense to build something to the smaller devices first and add the nicer extended versions in after. We were finding that building two different versions of everything was getting in the way of contributors willing to work on the DApp. Check the issue #563 to see screenshots of the intended design/behaviour of the menu for desktop/larger screens

**Comment by SamusElderg** [comment]
'POOLS' Page
This page is very far from the intended design; this is actually meant to be a user dashboard to perform all the user's functions and/or navigate the dapp. However that's not really priority until later on so for now its just one small piece of that intended design 😆 chance why it makes little sense to call it 'Overview' or 'DashBoard' as you mentioned. As i mentioned above; this will be changed to 'Pools', it was a good suggestion and one that was already on the minds of a lot of us.

Also whilst this page has changed a lot since you did up your PDF; it's still not anywhere near what it will be eventually; at some point when it moves up the priority list ill create an issue on this and pop up the screenshots of the mockups so you can see the intended 'pools' design is very similar to your mockups (for non-mobile users obviously) sorry buddy, i maybe should have sent some of the mockups before you spent time on them but i wasn't aware you were going to do full mockups of pages that we already have sorted!
