### ISSUE TITLE
BUG | Language popup position

### ISSUE THREAD

**Issue by jejopl** [spartan-protocol/SpartanProtocol-DAppV2#823]
Something weird is happening with language popup on firefox. 
It's going to the proper position after window resizing

https://user-images.githubusercontent.com/32012330/178225966-f17f53fc-1678-49a7-96f8-28f8f1d9c285.mov

**Comment by SamusElderg** [comment]
Also, the arrow position (not centred). These apply to all popovers since i broke it with the dependency upgrade a month or two ago. Namely the Create-react-app version upgrade (and/or react-bootstrap). Ill have a little peak at the deps and see if there is anything in the repos that suggest this was a known issue or if its particular to us
